### ISSUE TITLE
holidays for each state?

### ISSUE THREAD

**Issue by xwl** [rudolfochrist/german-holidays#1]
is it possible to define holidays for each state? according to http://www.holidays-info.com/Holidays-Germany/2015/holidays_2015.html, it is not straightforwad to know which holiday in which state.

e.g., for BW state, user can simply say 

(setq holiday-other-holidays holiday-german-BW-holidays)

**Comment by rudolfochrist** [comment]
Thanks for the great idea. After the next MELPA build, state specific holidays should be available.
